# Generated by Django 4.2.3 on 2023-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samdjangoproject', '0006_people_city_people_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(default='Nairobi', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.CharField(default='Kenya', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(default=1, max_length=30),
        ),
    ]
